### ISSUE TITLE
Issues with the current code.

### ISSUE THREAD

**Issue by khandelwaludit** [Pranavbhartia/RidersParadise#1]
1. You have created 5 fragments for five different pages but all of them have the same piece of code albeit the layout.xml file. Try passing the layout to all these files.
2. You copied the comment from some class and modified the classname but you have not introduced the methods that are mentioned in the fragment.
3.  There seems to be an unnecessary hierarchy added in the xml due to framelayout. Do you really need it ? You can remove it and still make it work.
4. **[Suggestion]** Your image size is big but you are showing a 160X160 image. It seems like a placeholder and does not give an enriching experience.  Try expanding them to fit the width of the screen. Let the height vary. 
5. Try reusing code. There is a lot of repeat code in terms of layout as well. You could have defined a layout with image and text view and initialized all fragments with the same and pass the text and image src to make the difference.

In case you want to do some specific stuff in all of the fragments, then it makes sense to have different fragments for different tabs.

**Comment by Pranavbhartia** [comment]
Made the changes accordingly, please verify once
